In [28]:
import numpy as np
import pandas as pd
from scipy.linalg import solve

In [29]:
#LU Разложение L part
def HaussL(A):
    f=np.linalg.det(A)
    if f!=0:
        number=len(A)
        An_1=np.array([[0.0 for j in range(number)] for i in range(number)])
        for i in range (len(A)):
            for j in range(len(A)):
                An_1[i,j]=A[i,j]
        lmatr=np.diag(np.full(number,1))

        for i in range(number):
            mi=np.array([[0.0 for m in range(number)] for k in range(number)])
            mi_1=np.array([[0.0 for m in range(number)] for k in range(number)])
            for j in range(i+1,number):
                mi[j,i]=-An_1[j,i]/An_1[i,i]
                mi_1[j,i]=An_1[j,i]/An_1[i,i]
            for k in range (number):
                mi[k,k]=1
                mi_1[k,k]=1
            An_1=mi.dot(An_1)
            lmatr=lmatr.dot(mi_1)
        return lmatr

In [30]:
#LU Разложение U 
def HaussU(A):
    f=np.linalg.det(A)
    if f!=0:
        number=len(A)
        An_1=np.array([[0.0 for j in range(number)] for i in range(number)])
        for i in range (len(A)):
            for j in range(len(A)):
                An_1[i,j]=A[i,j]

        for i in range(number):
            mi=np.array([[0.0 for m in range(number)] for k in range(number)])
            for j in range(i+1,number):
                mi[j,i]=-An_1[j,i]/An_1[i,i]
            for k in range (number):
                mi[k,k]=1
            An_1=mi.dot(An_1)
        return An_1

In [31]:
def Ncond(A):
#Спектральный критерий обусловленности
    normA=np.linalg.norm(A, ord=1)
    A_1=np.linalg.inv(A)
    normA_1=np.linalg.norm(A_1, ord=1)
    conds=normA*normA_1
#Объемный критерий (критерий Ортеги)
    number=len(A)
    condv=1
    for i in range(number):
        colsum=0
        for j in range(number):
            colsum=colsum+A[i][j]
        colsum=np.sqrt(colsum)
        condv=condv*colsum
    detA=abs(np.linalg.det(A))
    condv=condv/detA
#Угловой критерий
    pros=[]
    for i in range(number):
        Asum=0
        A_1sum=0
        for j in range(number):
            Asum=Asum+A[i][j]*A[i][j]
            A_1sum=Asum+A_1[i][j]*A_1[i][j]
        pros.append(np.sqrt(Asum*A_1sum))
    conda=max(pros)
    
    cond=[]
    cond.append(conds)
    cond.append(condv)
    cond.append(conda)
    return cond

In [32]:
#cond для A,L,U
def Filling(A):
    U=HaussU(A)
    L=HaussL(A)
    resA=Ncond(A)
    resL=Ncond(L)
    resU=Ncond(U)
    conds=['spectral','volume','angular']
    data = {'name':[],'cond': [], 'num': []}
    df = pd.DataFrame(data)
    
    for j in range(3):
        new_row = pd.DataFrame({'name':'A','cond':conds[j], 'num': resA[j]}, index = [0])
        df = pd.concat([df, new_row])
    for j in range(3):
        new_row = pd.DataFrame({'name':'L','cond':conds[j], 'num': resL[j]}, index = [0])
        df = pd.concat([df, new_row])
    for j in range(3):
        new_row = pd.DataFrame({'name':'U','cond':conds[j], 'num': resU[j]}, index = [0])
        df = pd.concat([df, new_row])
    
    print(df)

In [56]:
#Регуляризация
def Reg(A,x0):
    data = {'alpha': [],'spectral':[],'volume': [], 'angular': [],'||x-x~||':[]}
    df = pd.DataFrame(data)
    u=a.dot(x0)
    for number in range(12,0,-1):
#16
#a*a+alphaE
        acon=np.matrix.conjugate(A)
        e=np.diag(np.full(len(A),1))
        alpha=10**(-(number))
        lp=A.dot(acon)+alpha*e
        res=Ncond(lp)

#a*u
        rp=acon.dot(u)

#
        z1=solve(lp,rp)
        f=z1-x0
        new_row = pd.DataFrame({'alpha': alpha,'spectral':res[0],'volume': res[1], 'angular': res[2],'||x-x~||':np.linalg.norm(f, ord=1)}, index = [0])
        df=pd.concat([df, new_row])
    print (df)

In [34]:
#LU test good
a = np.array([[4,2,0,0],[2,5,2,0],[0,2,6,2],[0,0,2,7]])
b=np.array([-0.393, -0.389,-0.393, -0.389])
a

array([[4, 2, 0, 0],
       [2, 5, 2, 0],
       [0, 2, 6, 2],
       [0, 0, 2, 7]])

In [35]:
U=HaussU(a)
U

array([[4. , 2. , 0. , 0. ],
       [0. , 4. , 2. , 0. ],
       [0. , 0. , 5. , 2. ],
       [0. , 0. , 0. , 6.2]])

In [36]:
L=HaussL(a)
L

array([[1. , 0. , 0. , 0. ],
       [0.5, 1. , 0. , 0. ],
       [0. , 0.5, 1. , 0. ],
       [0. , 0. , 0.4, 1. ]])

In [37]:
Filling(a)

  name      cond        num
0    A  spectral   6.048387
0    A    volume   0.140552
0    A   angular  53.013006
0    L  spectral   2.775000
0    L    volume   1.774824
0    L   angular   1.582909
0    U  spectral   3.075000
0    U    volume   0.079692
0    U   angular  38.453005


In [38]:
x0=solve(a,b)
z=solve(L.dot(U),b)
print(x0)
print(z)

[-0.08466532 -0.02716935 -0.04191129 -0.04359677]
[-0.08466532 -0.02716935 -0.04191129 -0.04359677]


In [39]:
#LU test not so good
a = np.array([[1,0.99],[0.99,0.98]])
b=np.array([-0.393, -0.389])
a

array([[1.  , 0.99],
       [0.99, 0.98]])

In [40]:
U=HaussU(a)
U

array([[ 1.0e+00,  9.9e-01],
       [ 0.0e+00, -1.0e-04]])

In [41]:
L=HaussL(a)
L

array([[1.  , 0.  ],
       [0.99, 1.  ]])

In [55]:
Filling(a)

  name      cond            num
0    A  spectral   9.087772e+18
0    A    volume  4.623343e+272
0    A   angular   5.492804e+15
0    L  spectral   1.626193e+06
0    L    volume   2.152743e+27
0    L   angular   2.334559e+07
0    U  spectral   1.462044e+18
0    U    volume            NaN
0    U   angular   4.936996e+11


C:\Users\temur\AppData\Local\Temp\ipykernel_13984\3363458092.py:14: RuntimeWarning: invalid value encountered in sqrt
  colsum=np.sqrt(colsum)


In [43]:
x0=solve(a,b)
z=solve(L.dot(U),b)
print(x0)
print(z)

[ 0.3 -0.7]
[ 0.3 -0.7]


In [44]:
#LU test bad
a = np.array([[1.2969, 0.8648],[0.2161,0.1441]])
b=np.array([-0.393, -0.389])
a

array([[1.2969, 0.8648],
       [0.2161, 0.1441]])

In [45]:
U=HaussU(a)
U

array([[1.29690000e+00, 8.64800000e-01],
       [0.00000000e+00, 7.71069472e-09]])

In [46]:
L=HaussL(a)
L

array([[1.        , 0.        ],
       [0.16662811, 1.        ]])

In [47]:
Filling(a)

  name      cond           num
0    A  spectral  3.270652e+08
0    A    volume  8.824083e+07
0    A   angular  1.348042e+08
0    L  spectral  1.361021e+00
0    L    volume  1.080106e+00
0    L   angular  1.443629e+00
0    U  spectral  2.803509e+08
0    U    volume  1.291054e+04
0    U   angular  1.348042e+08


In [48]:
x0=solve(a,b)
z=solve(L.dot(U),b)
print(x0)
print(z)

[ 27977590.04349676 -41956680.06523005]
[ 27977590.04349676 -41956680.06523005]


In [49]:
#hilbert n=20
number=20
a = np.array([[0.0 for j in range(number)] for i in range(number)])
for i in range (number):
    for j in range(number):
        a[i,j]=1/(i+j+1)
x0=np.array([1 for k in range(number)])

In [57]:
Reg(a,x0)

          alpha      spectral         volume       angular    ||x-x~||
0  1.000000e-12  1.924675e+13  7.391975e+248  1.487133e+11    1.498381
0  1.000000e-11  1.930439e+12  1.067044e+231  1.591492e+10    2.195514
0  1.000000e-10  1.907981e+11  6.663428e+212  1.698589e+09    3.676230
0  1.000000e-09  1.952613e+10  1.257452e+194  1.817868e+08    6.369290
0  1.000000e-08  1.916848e+09  9.319742e+174  1.908242e+07    9.308517
0  1.000000e-07  1.932425e+08  2.099746e+155  2.022134e+06   17.033163
0  1.000000e-06  1.907831e+07  1.660214e+135  2.101761e+05   23.793829
0  1.000000e-05  1.886254e+06  3.864156e+114  2.197008e+04   42.362813
0  1.000000e-04  1.845183e+05   2.863766e+93  2.264730e+03   58.842102
0  1.000000e-03  1.766724e+04   5.750809e+71  2.335262e+02   94.518352
0  1.000000e-02  1.793646e+03   3.432243e+49  2.395824e+01  131.960086
0  1.000000e-01  1.824189e+02   8.113033e+26  6.032629e+00  184.560829


In [58]:
x0=np.array([k for k in range(number)])
Reg(a,x0)

          alpha      spectral         volume       angular    ||x-x~||
0  1.000000e-12  1.924675e+13  7.391975e+248  1.487133e+11    1.498381
0  1.000000e-11  1.930439e+12  1.067044e+231  1.591492e+10    2.195514
0  1.000000e-10  1.907981e+11  6.663428e+212  1.698589e+09    3.676230
0  1.000000e-09  1.952613e+10  1.257452e+194  1.817868e+08    6.369290
0  1.000000e-08  1.916848e+09  9.319742e+174  1.908242e+07    9.308517
0  1.000000e-07  1.932425e+08  2.099746e+155  2.022134e+06   17.033163
0  1.000000e-06  1.907831e+07  1.660214e+135  2.101761e+05   23.793829
0  1.000000e-05  1.886254e+06  3.864156e+114  2.197008e+04   42.362813
0  1.000000e-04  1.845183e+05   2.863766e+93  2.264730e+03   58.842102
0  1.000000e-03  1.766724e+04   5.750809e+71  2.335262e+02   94.518352
0  1.000000e-02  1.793646e+03   3.432243e+49  2.395824e+01  131.960086
0  1.000000e-01  1.824189e+02   8.113033e+26  6.032629e+00  184.560829


In [59]:
#hilbert  n=25
number=25
a = np.array([[0.0 for j in range(number)] for i in range(number)])
for i in range (number):
    for j in range(number):
        a[i,j]=1/(i+j+1)
x0=np.array([1 for k in range(number)])
Reg(a,x0)

          alpha      spectral         volume       angular  ||x-x~||
0  1.000000e-12  1.924675e+13  7.391975e+248  1.487133e+11  0.011638
0  1.000000e-11  1.930439e+12  1.067044e+231  1.591492e+10  0.017415
0  1.000000e-10  1.907981e+11  6.663428e+212  1.698589e+09  0.033495
0  1.000000e-09  1.952613e+10  1.257452e+194  1.817868e+08  0.060420
0  1.000000e-08  1.916848e+09  9.319742e+174  1.908242e+07  0.101768
0  1.000000e-07  1.932425e+08  2.099746e+155  2.022134e+06  0.199656
0  1.000000e-06  1.907831e+07  1.660214e+135  2.101761e+05  0.319476
0  1.000000e-05  1.886254e+06  3.864156e+114  2.197008e+04  0.631298
0  1.000000e-04  1.845183e+05   2.863766e+93  2.264730e+03  1.055381
0  1.000000e-03  1.766724e+04   5.750809e+71  2.335262e+02  1.950202
0  1.000000e-02  1.793646e+03   3.432243e+49  2.395824e+01  3.650405
0  1.000000e-01  1.824189e+02   8.113033e+26  6.032629e+00  6.308056


In [53]:
x0=np.array([k for k in range(number)])

In [60]:
Reg(a,x0)

          alpha      spectral         volume       angular  ||x-x~||
0  1.000000e-12  1.924675e+13  7.391975e+248  1.487133e+11  0.011638
0  1.000000e-11  1.930439e+12  1.067044e+231  1.591492e+10  0.017415
0  1.000000e-10  1.907981e+11  6.663428e+212  1.698589e+09  0.033495
0  1.000000e-09  1.952613e+10  1.257452e+194  1.817868e+08  0.060420
0  1.000000e-08  1.916848e+09  9.319742e+174  1.908242e+07  0.101768
0  1.000000e-07  1.932425e+08  2.099746e+155  2.022134e+06  0.199656
0  1.000000e-06  1.907831e+07  1.660214e+135  2.101761e+05  0.319476
0  1.000000e-05  1.886254e+06  3.864156e+114  2.197008e+04  0.631298
0  1.000000e-04  1.845183e+05   2.863766e+93  2.264730e+03  1.055381
0  1.000000e-03  1.766724e+04   5.750809e+71  2.335262e+02  1.950202
0  1.000000e-02  1.793646e+03   3.432243e+49  2.395824e+01  3.650405
0  1.000000e-01  1.824189e+02   8.113033e+26  6.032629e+00  6.308056
